name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

permissions: {}

jobs:
  build:
    permissions:
      contents: read
      actions: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true

      - uses: extractions/setup-just@v4

      - name: Install deps
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: beep ffmpeg zip libopus0 libvorbis0a libvorbisenc2 libmp3lame0
          version: 1.0

      - name: Build
        run: just precheck build

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: piezo-sounds
          path: |
            piezo_sounds.zip

  release:
    needs: build
    if: github.event_name == 'release'
    permissions:
      contents: write
      id-token: write
      attestations: write
      actions: read

    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: piezo-sounds

      - name: Upload to release
        run: gh release upload ${{ github.event.release.tag_name }} piezo_sounds.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
