name: Release

on:
  release:
    types: [published]

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true

      - uses: extractions/setup-just@v4

      - name: Install deps
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo -E apt-get update -qq
          sudo -E apt-get install -y -qq beep ffmpeg zip

      - name: Build
        run: just build

      - name: Attest
        uses: actions/attest@v4
        with:
          subject-path: |
            piezo_sounds.zip
            out/opus/*.opus

      - name: Upload to release
        run: gh release upload ${{ github.event.release.tag_name }} piezo_sounds.zip out/opus/*.opus
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
