name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true

      - name: Install deps
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo -E apt-get update -qq
          sudo -E apt-get install -y -qq just ffmpeg zip

      - name: Build
        run: just build

      - name: Upload piezo_sounds.zip to release
        run: gh release upload ${{ github.event.release.tag_name }} piezo_sounds.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
